error = load('f_error.txt');
error2 = load('f_error2.txt');
eps = load('f_eps.txt');
x = load('f_x.txt');
x2 = load('f_x2.txt');
y = load('f_y.txt');
runge = load('f_runge.txt');
runge2 = load('f_runge2.txt');
step_length = load('f_step_length.txt');
step_length2 = load('f_step_length2.txt');
len1 = length(runge);
len2 = length(x);
len3 = length(runge2);
len4 = length(x2);
len5 = length(y);
figure;
plot(x(1:30), y, 'r');
hold on;
finish = 30 + step_length(1);
plot(x(1:step_length(1)), runge(1:step_length(1)), 'b');
start = finish + 1;
start2 = 1 + step_length2(0);
plot(x(start:end), runge(start2:end), 'g');
xlabel('x');
ylabel('y', 'Rotation', 0);
legend('Функция', 'Эйлер1', 'Эйлер2');