epsilon = load('f_epsilon.txt');
error = load('f_error.txt');
integral = load('f_integral.txt');
iterations = load('f_iterations.txt');
figure;
loglog(epsilon,error);
hold on;
grid on;
title('Dependence of the actual error on the specified accuracy(epsilon)');
loglog(epsilon,epsilon);
ylabel('Actual error');
xlabel('\epsilon');
legend('Actual error','Bisector');
figure;
semilogx(epsilon,iterations);
ylabel('Iterations');
xlabel('\epsilon');
hold on;
grid on;
title('Dependence of the iterations on the specified accuracy(epsilon)');
